apiVersion: v1
kind: Service
metadata:
  name: nationalparks
  namespace: scsk-cd-dev
  labels:
    app: nationalparks
    app.kubernetes.io/component: nationalparks
    app.kubernetes.io/instance: nationalparks
    app.kubernetes.io/name: nationalparks
    app.kubernetes.io/part-of: nationalparks-git-app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
    - name: metrics
      port: 8778
      targetPort: 8778
      protocol: TCP
  selector:
    app: nationalparks
